#!/bin/bash
MACADDRS=($(ip -o link | grep -E '(eno.*|enp.*|ens.*)' | grep -v '@' | awk '{print $(NF-2)}' | awk -F'\' '{print $1}'))

TEMPFILE=$(mktemp /root/UNCONFIG-XXXXXXXX)
UNCONFIG="/root/UNCONFIG"

printf "%s\n" "${MACADDRS[@]}" > "${TEMPFILE}"
sort -o "${TEMPFILE}" "${TEMPFILE}"

NEWMD5=$(md5sum "${TEMPFILE}" | awk '{print $1}')

if [ ! -f "${UNCONFIG}" ]; then
    echo "First time running, unconfig ssh"
    cp "${TEMPFILE}" "${UNCONFIG}"
    /usr/bin/sys-unconfig -ssh
else
    OLDMD5=$(md5sum "${UNCONFIG}" | awk '{print $1}')
    if [ "${NEWMD5}" != "${OLDMD5}" ]; then
        echo "New Device installed, unconfig ssh"
        cp "${TEMPFILE}" "${UNCONFIG}"
        /usr/bin/sys-unconfig -ssh
    else
        echo "No new device installed, do nothing"
    fi
fi

rm "${TEMPFILE}"
